default_context:
  name: "gixpert"
  version: "0.1.0"
  slug: "gixpert"
  command: "gixpert"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "y"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "GI Encodscopy using Deep Learning"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "gi endoscopy deep learning"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "gixpert"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "gixpert"
  github_action: "y"
  ml: "y"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/gixpert"