name: Template

on:
  push:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  template:
    name: Template
    runs-on: ubuntu-latest
    steps:
      - uses: achillesrasquinha/boilpy-action
      - name: Updating template
        run: |
          echo "Updating template..."