name: Docker

on: [push, pull_request]

env:
  ENVIRONMENT: test
  VERBOSE: true
  TERM: xterm
  
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: ${{ github.actor }}
  PROJECT: ${{ github.event.repository.name }}

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Login to Registry
        run: |
          echo $GITHUB_TOKEN | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin
      - name: Build Image
        run: |
          make docker-build
      - name: Push Image
        run: |
          make docker-push
  
  build-singularity:
    needs:
      - build-docker

    name: Build Singularity
    runs-on: ubuntu-latest

    container:
      image: quay.io/singularity/docker2singularity
      options: --privileged
    
    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Increase Disk Space
        run: |
          rm -rf /host/{usr/share/dotnet,usr/local/lib/android,opt/ghc}
          patch /docker2singularity.sh ./ci/script/docker2singularity.patch
      - name: Login to Registry
        run: |
          echo $GITHUB_TOKEN | singularity remote login -u ${DOCKER_USERNAME} --password-stdin oras://${DOCKER_REGISTRY}
      - name: Build SIF File
        run: |
          DOCKER_IMAGE="${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${PROJECT}"
          SINGULARITY_IMAGE="$(echo -n ${DOCKER_IMAGE} | tr -c '[:alnum:].' '-').sif"

          docker-entrypoint.sh /docker2singularity.sh \
            --name ${SINGULARITY_IMAGE} \
             ${DOCKER_IMAGE}

          singularity push /output/${SINGULARITY_IMAGE} oras://${DOCKER_REGISTRY}/${DOCKER_USERNAME}/${PROJECT}:singularity