name: Model CI

on: [push, pull_request]

env:
  PIP_USE_DEPRECATED: "legacy-resolver"

  DEEPLY_WEIGHTS_AND_BIASES_API_KEY: ${{ secrets.WANDB_API_KEY }}
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

# concurrency: 
#   group: ${{ github.head_ref }}
#   cancel-in-progress: true

jobs:
  train:
    name: Train
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - uses: actions/setup-python@v2
        name: Set up Python 3.8
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          python setup.py develop
      - name: Run Pipeline
        run: |
          bpyutils --run-ml gixpert -p "check=True; artifacts_path=./artifacts.zip"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: train-artifacts
          path: ./artifacts.zip