name: Model CI

on: [push, pull_request]

env:
  PIP_USE_DEPRECATED: "legacy-resolver"

jobs:
  train:
    name: Train
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/achillesrasquinha/dl

    steps:
      - uses: actions/checkout@v2
      - name: Show ref
        run: |
          echo "Checking out $GITHUB_REF..."
      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt
          python setup.py develop
      - name: Run Pipeline
        run: |
          bpyutils --run-ml gixpert -p "artifacts_path=./artifacts.zip"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: train-artifacts
          path: ./artifacts.zip